### ISSUE TITLE
Native Library is not Recognized inside Docker

### ISSUE THREAD

**Issue by putraxor** [dart-lang/dart_docker#32]
docker image from google/dart-runtime and use dependency
```
dependencies:
  sqlite:
    git: 
      url: https://github.com/putraxor/dart-sqlite
```
dart-sqlite use native library libdart_sqlite.so but when I run it inside docker, it always complains 
```
libdart_sqlite.so: cannot open shared object file: No such file or directoryerror: library handler failed
```

this is my Dockerfile
```
FROM google/dart-runtime
USER root
RUN pub upgrade 
```
