### ISSUE TITLE
error for google/dart-runtime

### ISSUE THREAD

**Issue by v7lin** [dart-lang/dart_docker#33]
在我写的 Demo [v7lin/simple_pub_server](https://github.com/v7lin/simple_pub_server) 中使用 google/dart-runtime 镜像，无法通过http请求访问。

Dockerfile
````
FROM google/dart-runtime:2.2.0

MAINTAINER v7lin <v7lin@qq.com>
````
docker-compose.yml
````
# 版本
version: "3.7"

# 服务
services:

  pub_server:
    container_name: pub_server
    image: v7lin/simple_pub_server
    restart: always
    ports:
      - 80:8080
    volumes:
      - ../dev-ops-repo/pub_server:/tmp/package-db
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
      - PUB_SERVER_REPOSITORY_DATA=/tmp/package-db
````

[vishnubob/wait-for-it](https://github.com/vishnubob/wait-for-it)
````
***:wait-for-it v7lin$ ./wait-for-it.sh pub.haitanyule.com:80
wait-for-it.sh: waiting 15 seconds for pub.haitanyule.com:80
wait-for-it.sh: timeout occurred after waiting 15 seconds for pub.haitanyule.com:80
````
