### ISSUE TITLE
Document that pubspec cannot use paths that are outside of project

### ISSUE THREAD

**Issue by butlermatt** [dart-lang/dart_docker#4]
Building an app which contains a dependency that is located outside of the project will not work. For instance:

```
My_project \
My_project \ pubspec.yaml
My_project \ pubspec.lock
My_project \ Dockerfile
My_project \ bin \ server.dart
```

Where pubspec contains

```
...
dependencies:
  my_dep:
    path: ../my_dep/
```
