### ISSUE TITLE
docker-compose support?

### ISSUE THREAD

**Issue by e-belair** [dart-lang/dart_docker#51]
Hi, is there a docker-compose support for dart-runtime?
I get this error when I try to make it working:
```
Error: Could not resolve the package 'args' in 'package:args/args.dart'.
Error: Could not resolve the package 'shelf' in 'package:shelf/shelf.dart'.
Error: Could not resolve the package 'shelf' in 'package:shelf/shelf_io.dart'.
bin/server.dart:3:8: Error: Not found: 'package:args/args.dart'
import 'package:args/args.dart';
       ^
bin/server.dart:4:8: Error: Not found: 'package:shelf/shelf.dart'
import 'package:shelf/shelf.dart' as shelf;
       ^
bin/server.dart:5:8: Error: Not found: 'package:shelf/shelf_io.dart'
import 'package:shelf/shelf_io.dart' as io;
       ^
bin/server.dart:33:1: Error: Type 'shelf.Response' not found.
shelf.Response _echoRequest(shelf.Request request) =>
^^^^^^^^^^^^^^
bin/server.dart:33:29: Error: Type 'shelf.Request' not found.
shelf.Response _echoRequest(shelf.Request request) =>
                            ^^^^^^^^^^^^^
bin/server.dart:11:16: Error: Method not found: 'ArgParser'.
  var parser = ArgParser()..addOption('port', abbr: 'p');
               ^^^^^^^^^
bin/server.dart:25:29: Error: Method not found: 'Pipeline'.
  var handler = const shelf.Pipeline()
                            ^^^^^^^^
```
docker-compose:
```yml
version: "3"

services:
  dart:
    build:
      context: ./
      dockerfile: Dockerfile
    image: google/dart-runtime
    ports:
      - 8080:8080
    container_name: dart_srv
    networks:
      - frontend
      - backend
    volumes:
      - ./:/app
networks:
  frontend:
  backend:
```
Dockerfile:
```
FROM google/dart-runtime
```
The structure of my app is from a dart server sample app

**Comment by bertrandmc** [comment]
Hi @e-belair, have you figured this out?

**Comment by e-belair** [comment]
I could figure out by removing the volume declaration and let the Dockerfile copy files on a virtual volume:
```yml
version: '3'
services:
  dart:
    build:
      context: ./
      dockerfile: Dockerfile
    image: dart_srv
    restart: always
    container_name: dart_srv
    networks:
      - backend
    volumes:
    - ./db:/app/db
    env_file:
      - .env
networks:
  backend:
    driver: bridge
```
Then the Dockerfile:
```dockerfile
FROM google/dart-runtime

WORKDIR /app
ADD pubspec.* /app/
RUN pub get
ADD . /app
RUN pub get --offline

CMD []

ENTRYPOINT ["/usr/bin/dart", "bin/server.dart"]
```
When you declare a local volume, the container read the .packages file that contains references to the host package's location. I also tried to remove it but it does not work. The only way I found is to let Docker copy files to the /app dir and then, create another local volume for the files I need to access or backup locally like db.
